### PR TITLE
Version 0.2.1

### PR DESCRIPTION
**Pull request by st3107**
https://github.com/xpdAcq/rapidz/releases/tag/0.2.1

### CODE REVIEW

**Review by mrakitin — COMMENTED** [review]
Could you please put a link to the corresponding tagged version in the description of the PR?

The update looks good. Were there new dependencies introduced?

**Comment by st3107** [comment]
No new dependencies. I just fixed some bugs in syntax due to the update of networkx.

**Review by mrakitin — APPROVED** [review]

**Comment by mrakitin** [comment]
Thank you, @st3107! Soon we'll have an auto-tick bot, and are going to have such PRs automatically created, such as in https://github.com/nsls-ii-forge/trio-feedstock/pull/5.

**Comment by st3107** [comment]
That would be great. I am looking forward to it.

**Pull request merged**
